#!/bin/sh

# remove empty folders

DAEMON=$1

find $HOME/Movies/torresmosTV -name .DS_Store -exec rm {} \;

for h in $(find $HOME/Movies/torresmosTV -type d -empty); do
	[ -z "$DAEMON" ] && echo $h
	rmdir $h
done