#!/bin/sh

# remove all colors from torresmosTV folders

for h in $HOME/Movies/torresmosTV/*;
do
	echo $h
	osascript -e "tell application \"Finder\" to set label index of alias POSIX file \"$h\" to 0"
done